RHEAGROUP/COMET-Server-Administration-Tool

Modules/Common/ViewModels/LoginViewModel.cs, Modules/Common/Views/Login.xaml.cs, Modules/Migration/Utils/Migration.cs, Modules/Migration/ViewModels/MigrationViewModel.cs, Modules/Migration/Views/Layout.xaml, Modules/Syncer/ViewModels/SyncerViewModel.cs, Modules/Syncer/Views/Layout.xaml
=> SAT migration improvements

Modules/StressGenerator/Behaviors/StressGeneratorBehavior.cs, Modules/StressGenerator/StressGenerator.csproj, Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs, Modules/StressGenerator/Views/Layout.xaml
=> Implement stress generator ui

appveyor.yml
=> fix release typo

README.md, appveyor.yml
=> add appveyor badges

Modules/StressGenerator/Utils/ElementDefinitionGenerator.cs, Modules/StressGenerator/Utils/IterationGenerator.cs, Modules/StressGenerator/Utils/ParameterGenerator.cs, Modules/StressGenerator/Utils/StressGenerator.cs, Modules/StressGenerator/Utils/StressGeneratorManager.cs, Modules/StressGenerator/ViewModels/StressGeneratorConfiguration.cs, Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs, Modules/StressGenerator/Views/Layout.xaml, Modules/StressGenerator/Views/Layout.xaml.cs
=> Implement stress generator business logic

appveyor.yml
=> WIP: Update CI/CD first round

CDP4-SAT-tests.nunit, CDP4-SAT.sln, Modules/Common/ViewModels/LoginViewModel.cs, Modules/StressGenerator.Tests/StressGenerator.Tests.csproj, Modules/StressGenerator.Tests/StressGeneratorTestFixture.cs, Modules/StressGenerator/Utils/ElementDefinitionGenerator.cs, Modules/StressGenerator/Utils/StressGenerator.cs, Modules/StressGenerator/ViewModels/StressGeneratorConfiguration.cs, README.md, appveyor.yml
=> Add tests for StressGenerator.

Modules/StressGenerator.Tests/StressGenerator.Tests.csproj
=> Bump package version for StressGenerator.Test project

Modules/Common/Common.csproj, Modules/Migration.Tests/Migration.Tests.csproj, Modules/Migration/Migration.csproj, Modules/Migration/Utils/Migration.cs, Modules/StressGenerator.Tests/StressGenerator.Tests.csproj, Modules/StressGenerator/StressGenerator.csproj, Modules/Syncer.Tests/Syncer.Tests.csproj, Modules/Syncer/Syncer.csproj, SAT.Tests/SAT.Tests.csproj, SAT/SAT.csproj, appveyor.yml
=> Merge development

Modules/Migration/Utils/Migration.cs, Modules/StressGenerator/Utils/StressGenerator.cs
=> #97 SAT migration should migrate all iterations, not just the last one

Modules/Syncer/ViewModels/SyncerViewModel.cs
SQ improvement as per https://sonarcloud.io/project/issues?id=RHEAGROUP_CDP4-SAT&issues=AXY9cakQa4fFpg_ThjBW&open=AXY9cakQa4fFpg_ThjBW
=> [Improve] SyncerViewModel as per SQ

Modules/Migration/Utils/Migration.cs
Code improvements as per SonarQube
=> [Improvement] SonarQube improvements

Modules/Common/Events/LogEvent.cs, Modules/Common/ViewModels/LoginViewModel.cs, Modules/Migration.Tests/LoginViewModelTestFixture.cs, Modules/Migration.Tests/PocoCardinalityTestFixture.cs, Modules/Migration/Utils/Migration.cs, Modules/Migration/ViewModels/FixCardinalityErrorsDialogViewModel.cs, Modules/Migration/ViewModels/MigrationViewModel.cs, Modules/Migration/Views/Layout.xaml, Modules/Migration/Views/Layout.xaml.cs, SAT/NLog.dll.nlog, SAT/SAT.csproj
=> #101 Migration improvements logging

Modules/Migration/Utils/Migration.cs, Modules/Migration/ViewModels/MigrationViewModel.cs
=> #33 Add cleanup after migration

Modules/Common/Events/LogoutAndLoginEvent.cs, Modules/Common/ViewModels/LoginViewModel.cs, Modules/Migration.Tests/LoginViewModelTestFixture.cs, Modules/Migration/Utils/Migration.cs, Modules/Migration/ViewModels/MigrationViewModel.cs
=> #109 Login on the target server with the new server credentials after migration process

Modules/Common/Common.csproj, Modules/Migration.Tests/Migration.Tests.csproj, Modules/Migration/Migration.csproj, Modules/StressGenerator.Tests/StressGenerator.Tests.csproj, Modules/StressGenerator/StressGenerator.csproj, Modules/Syncer.Tests/Syncer.Tests.csproj, Modules/Syncer/Syncer.csproj, SAT.Tests/SAT.Tests.csproj, SAT/SAT.csproj
=> #107 Retarget SDK to the newest version: 7.4.0.

Modules/Migration/Utils/Migration.cs
- Replace old import route with new one
- ```Parallel.ForEach``` for reading model's iterations
=> Reading iteration failed for models that have multiple iterations

Modules/Migration/Migration.csproj, Modules/Migration/Utils/Migration.cs, SAT/SAT.csproj
=> #119 Reactive UI crash

Modules/StressGenerator/StressGenerator.csproj, Modules/StressGenerator/Utils/IterationGenerator.cs, Modules/StressGenerator/Utils/StressGenerator.cs
=> #123 Add write retry on failure

Modules/Common/Events/LogEvent.cs, Modules/Common/ViewModels/BaseModuleViewModel.cs, Modules/Common/ViewModels/LoginViewModel.cs, Modules/Migration/Utils/Migration.cs, Modules/Migration/ViewModels/FixCardinalityErrorsDialogViewModel.cs, Modules/Migration/ViewModels/MigrationViewModel.cs, Modules/StressGenerator.Tests/StressGeneratorTestFixture.cs, Modules/StressGenerator/Utils/EngineeringModelSetupGenerator.cs, Modules/StressGenerator/Utils/GeneratorHelper.cs, Modules/StressGenerator/Utils/IterationGenerator.cs, Modules/StressGenerator/Utils/ParameterGenerator.cs, Modules/StressGenerator/Utils/StressGenerator.cs, Modules/StressGenerator/Utils/WriteHelper.cs, Modules/StressGenerator/ViewModels/StressGeneratorConfiguration.cs, Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs, Modules/StressGenerator/Views/Layout.xaml
=> #117 stress generator additional options changes

Modules/Common/ViewModels/BaseModuleViewModel.cs, Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs, Modules/Syncer/ViewModels/SyncerViewModel.cs
=> #81 Unify output messages mechanism

Modules/StressGenerator.Tests/StressGeneratorTestFixture.cs, Modules/StressGenerator/Utils/ParameterGenerator.cs, Modules/StressGenerator/Utils/StressGenerator.cs, Modules/StressGenerator/ViewModels/StressGeneratorConfiguration.cs, Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
=> #117 Add missing logs

Modules/Migration/Utils/Migration.cs, Modules/Syncer/Utils/ThingType.cs
=> CodeSmell S1135 - Update TODO comments

Modules/Migration.Tests/MigrationTestFixture.cs
=> CodeSmell CS1998 - This async method lacks 'await' operators

Modules/Migration/Utils/Migration.cs
=> CodeSmell S1481 - Remove the unused local variable 'zipSession'

Modules/Common/Common.csproj, Modules/Migration.Tests/Migration.Tests.csproj, Modules/Migration/Migration.csproj, Modules/Migration/Utils/Migration.cs, Modules/StressGenerator.Tests/StressGenerator.Tests.csproj, Modules/StressGenerator/StressGenerator.csproj, Modules/Syncer.Tests/Syncer.Tests.csproj, Modules/Syncer/Syncer.csproj, SAT.Tests/SAT.Tests.csproj, SAT/SAT.csproj
Stop message bus to send message to listeners in case of reading an iteration and/or open session.
=> #193 Support for open and read silently(no messagebus)
